// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTZvvlTrujecnzXZXsjDhY1ObjnNQSrNc',
    appId: '1:568967656217:web:49857b8011aa3aebcfcb88',
    messagingSenderId: '568967656217',
    projectId: 'flutter-homeassignment',
    authDomain: 'flutter-homeassignment.firebaseapp.com',
    storageBucket: 'flutter-homeassignment.firebasestorage.app',
    measurementId: 'G-98710XZJLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYC3sb95kTn3PjzCqX3hGjHwZjBvbq1c',
    appId: '1:568967656217:android:5e1c49af42353306cfcb88',
    messagingSenderId: '568967656217',
    projectId: 'flutter-homeassignment',
    storageBucket: 'flutter-homeassignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqsMZycHpIH0-ZhpVOPN5bXPc9AQTpIkA',
    appId: '1:568967656217:ios:023155a1e370ea2ccfcb88',
    messagingSenderId: '568967656217',
    projectId: 'flutter-homeassignment',
    storageBucket: 'flutter-homeassignment.firebasestorage.app',
    iosBundleId: 'com.example.homeAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqsMZycHpIH0-ZhpVOPN5bXPc9AQTpIkA',
    appId: '1:568967656217:ios:023155a1e370ea2ccfcb88',
    messagingSenderId: '568967656217',
    projectId: 'flutter-homeassignment',
    storageBucket: 'flutter-homeassignment.firebasestorage.app',
    iosBundleId: 'com.example.homeAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTZvvlTrujecnzXZXsjDhY1ObjnNQSrNc',
    appId: '1:568967656217:web:b477d3b0d52a25d4cfcb88',
    messagingSenderId: '568967656217',
    projectId: 'flutter-homeassignment',
    authDomain: 'flutter-homeassignment.firebaseapp.com',
    storageBucket: 'flutter-homeassignment.firebasestorage.app',
    measurementId: 'G-VE9M7PXEXQ',
  );
}
